using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


using System.IO;
using Newtonsoft.Json;
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using WildGrassPOSLibrary.Models;
using System.Windows;
using Firebase.Storage;


using WildGrass_Desktop_f8.Functions;
using System.Windows.Controls;
using System.Threading;

namespace WildGrass_Desktop_f8.Services
{
    internal class BookKeepingSettingsServicesClass
    {
        //ID's
        string uid = "";
        string bid = "";
        string eid = "";


        int duration = 2000;
        int numberOfTries = 3;

        DatabaseDirectoryServicesClass DatabaseDirectory = new();
        WildGrassPOSLibrary.Services.PrevalentClass prevelantClass = new();
        StandardFirebaseOperationsClass standardFirebaseOperationsClass = new StandardFirebaseOperationsClass();

        IFirebaseConfig ifc = new FirebaseConfig
        {
            AuthSecret = "btiSgvaHMXQWODLMFQSgFBHLJuBykOfzwu9xbfdV",
            BasePath = "https://long-walk-pos.firebaseio.com/"
        };

        IFirebaseClient client;

        private void setup()
        {
            try
            {
                client = new FireSharp.FirebaseClient(ifc);
            }
            catch (Exception)
            {
                //what to do
            }
        }


        //Update
        public void SetAutoGenerateDNote(bool autoGenerate, Button control, Action<bool> method, bool update)
        {
            bool success = false;
            eid = prevelantClass.getEid();
            setup();

            for (int i = 0; i < numberOfTries; i++)
            {
                try
                {
                    FirebaseResponse firebase = client.Set(DatabaseDirectory.Settings() + "/bookKeepingSettings/AutoGenerateDeliveryNote", autoGenerate);


                    if (update)
                    {
                        standardFirebaseOperationsClass.UpdateVersion("settings");
                    }
                    standardFirebaseOperationsClass.activityLog("bookKeepingSettings", "settings", "Changed auto generate delivery note", eid);
                    success = true;
                    break;
                }
                catch (Exception)
                {
                    Thread.Sleep(duration);
                }
            }
            control.Dispatcher.BeginInvoke(
                System.Windows.Threading.DispatcherPriority.Normal,
                method, success);
        }

        public void SetupVatStandard(bool enable, Button control, Action<bool> method, bool update)
        {
            //enble continuous folio
            bool success = false;
            eid = prevelantClass.getEid();
            setup();

            for (int i = 0; i < numberOfTries; i++)
            {
                try
                {
                    FirebaseResponse firebase = client.Set(DatabaseDirectory.Settings() + "/bookKeepingSettings/TaxInvoiceStandard", enable);

                    if (!enable)
                    {
                        //kill mode enabled
                        FirebaseResponse res = client.Delete(DatabaseDirectory.Folios());
                    }
                    if (update)
                    {
                        standardFirebaseOperationsClass.UpdateVersion("settings");
                    }
                    standardFirebaseOperationsClass.activityLog("bookKeepingSettings", "settings", "Tax Invoicing Standard: " + enable.ToString(), eid);
                    success = true;
                    break;
                }
                catch (Exception)
                {
                    Thread.Sleep(duration);
                }
            }
            control.Dispatcher.BeginInvoke(
                System.Windows.Threading.DispatcherPriority.Normal,
                method, success);
            //generation of original and duplicate
        }

        public void SetupContinuous(string sdType)
        {

        }

        public void disableVatStandard()
        {

        }
    }
}
